# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogSelectWeek_Task4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class DialogWeeklyPlanELWorks(object):
    def setupUi(self, DialogWeeklyPlanELWorks):
        DialogWeeklyPlanELWorks.setObjectName("DialogWeeklyPlanELWorks")
        DialogWeeklyPlanELWorks.resize(904, 506)
        self.gridLayout = QtWidgets.QGridLayout(DialogWeeklyPlanELWorks)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(384, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.pushButtonOK = QtWidgets.QPushButton(DialogWeeklyPlanELWorks)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout.addWidget(self.pushButtonOK, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(DialogWeeklyPlanELWorks)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 3)
        self.lineEditRule = QtWidgets.QLineEdit(DialogWeeklyPlanELWorks)
        self.lineEditRule.setEnabled(True)
        self.lineEditRule.setText("")
        self.lineEditRule.setReadOnly(True)
        self.lineEditRule.setObjectName("lineEditRule")
        self.gridLayout.addWidget(self.lineEditRule, 0, 0, 1, 3)

        self.retranslateUi(DialogWeeklyPlanELWorks)
        self.pushButtonOK.clicked.connect(DialogWeeklyPlanELWorks.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogWeeklyPlanELWorks)

    def retranslateUi(self, DialogWeeklyPlanELWorks):
        _translate = QtCore.QCoreApplication.translate
        DialogWeeklyPlanELWorks.setWindowTitle(_translate("DialogWeeklyPlanELWorks", tr("DialogWeeklyPlanELWorks")))
        self.pushButtonOK.setText(_translate("DialogWeeklyPlanELWorks", tr("OK")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogWeeklyPlanELWorks1 = QtWidgets.QDialog()
    ui = DialogWeeklyPlanELWorks()
    ui.setupUi(DialogWeeklyPlanELWorks1)
    DialogWeeklyPlanELWorks1.show()
    sys.exit(app.exec_())
