# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogUpdateL_vol_works.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogUpdateL_vol_works(object):
    def setupUi(self, DialogUpdateL_vol_works):
        DialogUpdateL_vol_works.setObjectName("DialogUpdateL_vol_works")
        DialogUpdateL_vol_works.resize(566, 236)
        self.gridLayout = QtWidgets.QGridLayout(DialogUpdateL_vol_works)
        self.gridLayout.setObjectName("gridLayout")
        self.lWork_name = QtWidgets.QLabel(DialogUpdateL_vol_works)
        self.lWork_name.setObjectName("lWork_name")
        self.gridLayout.addWidget(self.lWork_name, 0, 0, 1, 1)
        self.lScope_of_work_per_floor = QtWidgets.QLabel(DialogUpdateL_vol_works)
        self.lScope_of_work_per_floor.setObjectName("lScope_of_work_per_floor")
        self.gridLayout.addWidget(self.lScope_of_work_per_floor, 1, 0, 1, 1)
        self.lScope_of_SMR_in_thousand_rub_per_floor = QtWidgets.QLabel(DialogUpdateL_vol_works)
        self.lScope_of_SMR_in_thousand_rub_per_floor.setObjectName("lScope_of_SMR_in_thousand_rub_per_floor")
        self.gridLayout.addWidget(self.lScope_of_SMR_in_thousand_rub_per_floor, 2, 0, 1, 1)
        self.lduration_of_work = QtWidgets.QLabel(DialogUpdateL_vol_works)
        self.lduration_of_work.setObjectName("lduration_of_work")
        self.gridLayout.addWidget(self.lduration_of_work, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(244, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.pushButtonUpdate = QtWidgets.QPushButton(DialogUpdateL_vol_works)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.gridLayout.addWidget(self.pushButtonUpdate, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.dBlScope_of_work_per_floor = QtWidgets.QDoubleSpinBox(DialogUpdateL_vol_works)
        self.dBlScope_of_work_per_floor.setDecimals(1)
        self.dBlScope_of_work_per_floor.setObjectName("dBlScope_of_work_per_floor")
        self.gridLayout.addWidget(self.dBlScope_of_work_per_floor, 1, 1, 1, 2)
        self.cBWork_name = QtWidgets.QComboBox(DialogUpdateL_vol_works)
        self.cBWork_name.setObjectName("cBWork_name")
        self.gridLayout.addWidget(self.cBWork_name, 0, 1, 1, 2)
        self.dBScope_of_SMR_in_thousand_rub_per_floor = QtWidgets.QDoubleSpinBox(DialogUpdateL_vol_works)
        self.dBScope_of_SMR_in_thousand_rub_per_floor.setDecimals(1)
        self.dBScope_of_SMR_in_thousand_rub_per_floor.setObjectName("dBScope_of_SMR_in_thousand_rub_per_floor")
        self.gridLayout.addWidget(self.dBScope_of_SMR_in_thousand_rub_per_floor, 2, 1, 1, 2)
        self.dBduration_of_work = QtWidgets.QDoubleSpinBox(DialogUpdateL_vol_works)
        self.dBduration_of_work.setDecimals(1)
        self.dBduration_of_work.setObjectName("dBduration_of_work")
        self.gridLayout.addWidget(self.dBduration_of_work, 3, 1, 1, 2)

        self.retranslateUi(DialogUpdateL_vol_works)
        QtCore.QMetaObject.connectSlotsByName(DialogUpdateL_vol_works)

    def retranslateUi(self, DialogUpdateL_vol_works):
        _translate = QtCore.QCoreApplication.translate
        DialogUpdateL_vol_works.setWindowTitle(_translate("DialogUpdateL_vol_works", tr("DialogUpdateL_vol_works")))
        self.lWork_name.setText(_translate("DialogUpdateL_vol_works", tr("Work_name")))
        self.lScope_of_work_per_floor.setText(_translate("DialogUpdateL_vol_works", tr("Scope_of_work_per_floor")))
        self.lScope_of_SMR_in_thousand_rub_per_floor.setText(_translate("DialogUpdateL_vol_works",
                                                                        tr("Scope_of_SMR_in_thousand_rub_per_floor")))
        self.lduration_of_work.setText(_translate("DialogUpdateL_vol_works", tr("Duration_of_work")))
        self.pushButtonUpdate.setText(_translate("DialogUpdateL_vol_works", tr("Update Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogUpdateL_vol_works = QtWidgets.QDialog()
    ui = Ui_DialogUpdateL_vol_works()
    ui.setupUi(DialogUpdateL_vol_works)
    DialogUpdateL_vol_works.show()
    sys.exit(app.exec_())
