# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogAddToReport_on_compl_works.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogAddToReport_on_compl_works(object):
    def setupUi(self, DialogAddToReport_on_compl_works):
        DialogAddToReport_on_compl_works.setObjectName("DialogAddToReport_on_compl_works")
        DialogAddToReport_on_compl_works.resize(440, 327)
        self.gridLayout = QtWidgets.QGridLayout(DialogAddToReport_on_compl_works)
        self.gridLayout.setObjectName("gridLayout")
        self.lwork_name_report = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lwork_name_report.setObjectName("lwork_name_report")
        self.gridLayout.addWidget(self.lwork_name_report, 0, 0, 1, 1)
        self.lbuilding_name = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lbuilding_name.setObjectName("lbuilding_name")
        self.gridLayout.addWidget(self.lbuilding_name, 1, 0, 1, 1)
        self.lunit = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lunit.setObjectName("lunit")
        self.gridLayout.addWidget(self.lunit, 2, 0, 1, 1)
        self.lvolume_per_object = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lvolume_per_object.setObjectName("lvolume_per_object")
        self.gridLayout.addWidget(self.lvolume_per_object, 3, 0, 1, 1)
        self.lact_am_work_performed = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lact_am_work_performed.setObjectName("lact_am_work_performed")
        self.gridLayout.addWidget(self.lact_am_work_performed, 4, 0, 1, 1)
        self.lst_date_act_am_work_perf = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lst_date_act_am_work_perf.setObjectName("lst_date_act_am_work_perf")
        self.gridLayout.addWidget(self.lst_date_act_am_work_perf, 5, 0, 1, 1)
        self.lend_date_act_am_work_perf = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lend_date_act_am_work_perf.setObjectName("lend_date_act_am_work_perf")
        self.gridLayout.addWidget(self.lend_date_act_am_work_perf, 6, 0, 1, 1)
        self.lremaining_volume = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.lremaining_volume.setObjectName("lremaining_volume")
        self.gridLayout.addWidget(self.lremaining_volume, 7, 0, 1, 1)
        self.ldate_of_remain_vol = QtWidgets.QLabel(DialogAddToReport_on_compl_works)
        self.ldate_of_remain_vol.setObjectName("ldate_of_remain_vol")
        self.gridLayout.addWidget(self.ldate_of_remain_vol, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.pushButtonADDData = QtWidgets.QPushButton(DialogAddToReport_on_compl_works)
        self.pushButtonADDData.setObjectName("pushButtonADDData")
        self.gridLayout.addWidget(self.pushButtonADDData, 9, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 9, 2, 1, 1)
        self.date_date_of_remain_vol = QtWidgets.QDateEdit(DialogAddToReport_on_compl_works)
        self.date_date_of_remain_vol.setObjectName("date_date_of_remain_vol")
        self.gridLayout.addWidget(self.date_date_of_remain_vol, 8, 1, 1, 2)
        self.sBremaining_volume = QtWidgets.QSpinBox(DialogAddToReport_on_compl_works)
        self.sBremaining_volume.setObjectName("sBremaining_volume")
        self.gridLayout.addWidget(self.sBremaining_volume, 7, 1, 1, 2)
        self.date_end_date_act_am_work_perf = QtWidgets.QDateEdit(DialogAddToReport_on_compl_works)
        self.date_end_date_act_am_work_perf.setObjectName("date_end_date_act_am_work_perf")
        self.gridLayout.addWidget(self.date_end_date_act_am_work_perf, 6, 1, 1, 2)
        self.date_st_date_act_am_work_perf = QtWidgets.QDateEdit(DialogAddToReport_on_compl_works)
        self.date_st_date_act_am_work_perf.setObjectName("date_st_date_act_am_work_perf")
        self.gridLayout.addWidget(self.date_st_date_act_am_work_perf, 5, 1, 1, 2)
        self.sBact_am_work_performed = QtWidgets.QSpinBox(DialogAddToReport_on_compl_works)
        self.sBact_am_work_performed.setObjectName("sBact_am_work_performed")
        self.gridLayout.addWidget(self.sBact_am_work_performed, 4, 1, 1, 2)
        self.sBvolume_per_object = QtWidgets.QSpinBox(DialogAddToReport_on_compl_works)
        self.sBvolume_per_object.setObjectName("sBvolume_per_object")
        self.gridLayout.addWidget(self.sBvolume_per_object, 3, 1, 1, 2)
        self.lineunit = QtWidgets.QLineEdit(DialogAddToReport_on_compl_works)
        self.lineunit.setObjectName("lineunit")
        self.gridLayout.addWidget(self.lineunit, 2, 1, 1, 2)
        self.cBbuilding_name = QtWidgets.QComboBox(DialogAddToReport_on_compl_works)
        self.cBbuilding_name.setObjectName("cBbuilding_name")
        self.gridLayout.addWidget(self.cBbuilding_name, 1, 1, 1, 2)
        self.linework_name_report = QtWidgets.QLineEdit(DialogAddToReport_on_compl_works)
        self.linework_name_report.setObjectName("linework_name_report")
        self.gridLayout.addWidget(self.linework_name_report, 0, 1, 1, 2)

        self.retranslateUi(DialogAddToReport_on_compl_works)
        QtCore.QMetaObject.connectSlotsByName(DialogAddToReport_on_compl_works)

    def retranslateUi(self, DialogAddToReport_on_compl_works):
        _translate = QtCore.QCoreApplication.translate
        DialogAddToReport_on_compl_works.setWindowTitle(_translate("DialogAddToReport_on_compl_works",
                                                                   tr("DialogAddToReport_on_compl_works")))
        self.lwork_name_report.setText(_translate("DialogAddToReport_on_compl_works", tr("work_name_report")))
        self.lbuilding_name.setText(_translate("DialogAddToReport_on_compl_works", tr("building_name")))
        self.lunit.setText(_translate("DialogAddToReport_on_compl_works", tr("unit")))
        self.lvolume_per_object.setText(_translate("DialogAddToReport_on_compl_works", tr("volume_per_object")))
        self.lact_am_work_performed.setText(_translate("DialogAddToReport_on_compl_works",
                                                       tr("act_am_work_performed")))
        self.lst_date_act_am_work_perf.setText(_translate("DialogAddToReport_on_compl_works",
                                                          tr("st_date_act_am_work_perf")))
        self.lend_date_act_am_work_perf.setText(_translate("DialogAddToReport_on_compl_works",
                                                           tr("end_date_act_am_work_perf")))
        self.lremaining_volume.setText(_translate("DialogAddToReport_on_compl_works", tr("remaining_volume")))
        self.ldate_of_remain_vol.setText(_translate("DialogAddToReport_on_compl_works", tr("date_of_remain_vol")))
        self.pushButtonADDData.setText(_translate("DialogAddToReport_on_compl_works", tr("Add Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddToReport_on_compl_works = QtWidgets.QDialog()
    ui = Ui_DialogAddToReport_on_compl_works()
    ui.setupUi(DialogAddToReport_on_compl_works)
    DialogAddToReport_on_compl_works.show()
    sys.exit(app.exec_())
