# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\Dialog_Add_Search_Delete_Data.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogDelADDSearch(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 466)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.rBl_of_vol_of_works = QtWidgets.QRadioButton(Dialog)
        self.rBl_of_vol_of_works.setObjectName("rBl_of_vol_of_works")
        self.gridLayout.addWidget(self.rBl_of_vol_of_works, 1, 1, 1, 1)
        self.rBam_works_per_building_GPM = QtWidgets.QRadioButton(Dialog)
        self.rBam_works_per_building_GPM.setObjectName("rBam_works_per_building_GPM")
        self.gridLayout.addWidget(self.rBam_works_per_building_GPM, 1, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 4, 0, 1, 5)
        self.PushSearchData = QtWidgets.QPushButton(Dialog)
        self.PushSearchData.setObjectName("PushSearchData")
        self.gridLayout.addWidget(self.PushSearchData, 5, 0, 1, 1)
        self.rBBuildingsData = QtWidgets.QRadioButton(Dialog)
        self.rBBuildingsData.setObjectName("rBBuildingsData")
        self.gridLayout.addWidget(self.rBBuildingsData, 0, 1, 1, 1)
        self.rBreport_on_compl_works = QtWidgets.QRadioButton(Dialog)
        self.rBreport_on_compl_works.setObjectName("rBreport_on_compl_works")
        self.gridLayout.addWidget(self.rBreport_on_compl_works, 1, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 5, 1, 1, 4)
        self.rBStateElemEst = QtWidgets.QRadioButton(Dialog)
        self.rBStateElemEst.setObjectName("rBStateElemEst")
        self.gridLayout.addWidget(self.rBStateElemEst, 0, 3, 1, 1)
        self.rBDirOfWorks = QtWidgets.QRadioButton(Dialog)
        self.rBDirOfWorks.setObjectName("rBDirOfWorks")
        self.gridLayout.addWidget(self.rBDirOfWorks, 0, 2, 1, 1)
        self.PushDeleteData = QtWidgets.QPushButton(Dialog)
        self.PushDeleteData.setObjectName("PushDeleteData")
        self.gridLayout.addWidget(self.PushDeleteData, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.PushAddData = QtWidgets.QPushButton(Dialog)
        self.PushAddData.setObjectName("PushAddData")
        self.gridLayout.addWidget(self.PushAddData, 0, 4, 1, 1)
        self.PushUpdateData = QtWidgets.QPushButton(Dialog)
        self.PushUpdateData.setObjectName("PushUpdateData")
        self.gridLayout.addWidget(self.PushUpdateData, 1, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", tr("Dialog_Add_Delete_Search_Data")))
        self.rBl_of_vol_of_works.setText(_translate("Dialog", tr("list_of_volume_of_works")))
        self.rBam_works_per_building_GPM.setText(_translate("Dialog",
                                                            tr("am_works_per_building_GPM")))
        self.PushSearchData.setText(_translate("Dialog", tr("Search Data")))
        self.rBBuildingsData.setText(_translate("Dialog", tr("reg_buildings_in_district")))
        self.rBreport_on_compl_works.setText(_translate("Dialog",
                                                        tr("report_on_compl_works")))
        self.rBStateElemEst.setText(_translate("Dialog", tr("state_element_estimates")))
        self.rBDirOfWorks.setText(_translate("Dialog", tr("directory_of_works")))
        self.PushDeleteData.setText(_translate("Dialog", tr("Delete Data")))
        self.label.setText(_translate("Dialog", tr("Show Data:")))
        self.PushAddData.setText(_translate("Dialog", tr("Add Data")))
        self.PushUpdateData.setText(_translate("Dialog", tr("Update Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DialogDelADDSearch()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
