# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogSolveTask1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogSolveTask1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1141, 355)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 2, 5, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.pushPrint = QtWidgets.QPushButton(Dialog)
        self.pushPrint.setObjectName("pushPrint")
        self.gridLayout.addWidget(self.pushPrint, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.pushShowMatrixDistr = QtWidgets.QPushButton(Dialog)
        self.pushShowMatrixDistr.setObjectName("pushShowMatrixDistr")
        self.gridLayout.addWidget(self.pushShowMatrixDistr, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 4, 1, 1)
        self.pushButtonSolveTask = QtWidgets.QPushButton(Dialog)
        self.pushButtonSolveTask.setObjectName("pushButtonSolveTask")
        self.gridLayout.addWidget(self.pushButtonSolveTask, 3, 5, 1, 1)
        self.pushButtonGetData = QtWidgets.QPushButton(Dialog)
        self.pushButtonGetData.setObjectName("pushButtonGetData")
        self.gridLayout.addWidget(self.pushButtonGetData, 3, 6, 1, 1)
        self.spinBoxSumTimeCons = QtWidgets.QSpinBox(Dialog)
        self.spinBoxSumTimeCons.setObjectName("spinBoxSumTimeCons")
        self.gridLayout.addWidget(self.spinBoxSumTimeCons, 1, 5, 1, 2)
        self.spinBoxAmObj = QtWidgets.QSpinBox(Dialog)
        self.spinBoxAmObj.setObjectName("spinBoxAmObj")
        self.gridLayout.addWidget(self.spinBoxAmObj, 0, 5, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog",
                                         tr("Entering the number of objects to solve the problem and "
                                            "the time of electrical installation work on the objects")))
        self.label.setText(_translate("Dialog", tr("Number of objects in the district")))
        self.label_2.setText(_translate("Dialog", tr("The total duration of work on all objects")))
        self.label_3.setText(_translate("Dialog", tr("Start date of the planned period")))
        self.pushPrint.setText(_translate("Dialog", tr("Interactions with the document")))
        self.pushShowMatrixDistr.setText(_translate("Dialog", tr("Matrix of distribution of workers")))
        self.pushButtonSolveTask.setText(_translate("Dialog", tr("Solve Task")))
        self.pushButtonGetData.setText(_translate("Dialog", tr("Get Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DialogSolveTask1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
