# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogUpdateRegBuildingsInDistrict.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogUpdateRegBuildingsInDistrict(object):
    def setupUi(self, DialogUpdateRegBuildingsInDistrict):
        DialogUpdateRegBuildingsInDistrict.setObjectName("DialogUpdateRegBuildingsInDistrict")
        DialogUpdateRegBuildingsInDistrict.resize(388, 250)
        self.gridLayout = QtWidgets.QGridLayout(DialogUpdateRegBuildingsInDistrict)
        self.gridLayout.setObjectName("gridLayout")
        self.lAmOfFloors = QtWidgets.QLabel(DialogUpdateRegBuildingsInDistrict)
        self.lAmOfFloors.setObjectName("lAmOfFloors")
        self.gridLayout.addWidget(self.lAmOfFloors, 0, 0, 1, 1)
        self.lAmOfEntrances = QtWidgets.QLabel(DialogUpdateRegBuildingsInDistrict)
        self.lAmOfEntrances.setObjectName("lAmOfEntrances")
        self.gridLayout.addWidget(self.lAmOfEntrances, 1, 0, 1, 1)
        self.lTotalFloors = QtWidgets.QLabel(DialogUpdateRegBuildingsInDistrict)
        self.lTotalFloors.setObjectName("lTotalFloors")
        self.gridLayout.addWidget(self.lTotalFloors, 2, 0, 1, 1)
        self.lBuilding_name_reg = QtWidgets.QLabel(DialogUpdateRegBuildingsInDistrict)
        self.lBuilding_name_reg.setObjectName("lBuilding_name_reg")
        self.gridLayout.addWidget(self.lBuilding_name_reg, 3, 0, 1, 1)
        self.lNumberOfBuilding = QtWidgets.QLabel(DialogUpdateRegBuildingsInDistrict)
        self.lNumberOfBuilding.setObjectName("lNumberOfBuilding")
        self.gridLayout.addWidget(self.lNumberOfBuilding, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.pushButtonUpdateData = QtWidgets.QPushButton(DialogUpdateRegBuildingsInDistrict)
        self.pushButtonUpdateData.setObjectName("pushButtonUpdateData")
        self.gridLayout.addWidget(self.pushButtonUpdateData, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.spinAmOfFloors = QtWidgets.QSpinBox(DialogUpdateRegBuildingsInDistrict)
        self.spinAmOfFloors.setObjectName("spinAmOfFloors")
        self.gridLayout.addWidget(self.spinAmOfFloors, 0, 1, 1, 2)
        self.spinAmOfEntrances = QtWidgets.QSpinBox(DialogUpdateRegBuildingsInDistrict)
        self.spinAmOfEntrances.setObjectName("spinAmOfEntrances")
        self.gridLayout.addWidget(self.spinAmOfEntrances, 1, 1, 1, 2)
        self.spinTotalAmFloors = QtWidgets.QSpinBox(DialogUpdateRegBuildingsInDistrict)
        self.spinTotalAmFloors.setObjectName("spinTotalAmFloors")
        self.gridLayout.addWidget(self.spinTotalAmFloors, 2, 1, 1, 2)
        self.lineBuilding_name_reg = QtWidgets.QLineEdit(DialogUpdateRegBuildingsInDistrict)
        self.lineBuilding_name_reg.setObjectName("lineBuilding_name_reg")
        self.gridLayout.addWidget(self.lineBuilding_name_reg, 3, 1, 1, 2)
        self.spinNumber_of_building = QtWidgets.QSpinBox(DialogUpdateRegBuildingsInDistrict)
        self.spinNumber_of_building.setObjectName("spinNumber_of_building")
        self.gridLayout.addWidget(self.spinNumber_of_building, 4, 1, 1, 2)

        self.retranslateUi(DialogUpdateRegBuildingsInDistrict)
        QtCore.QMetaObject.connectSlotsByName(DialogUpdateRegBuildingsInDistrict)

    def retranslateUi(self, DialogUpdateRegBuildingsInDistrict):
        _translate = QtCore.QCoreApplication.translate
        DialogUpdateRegBuildingsInDistrict.setWindowTitle(_translate("DialogUpdateRegBuildingsInDistrict",
                                                                     tr("DialogUpdateRegBuildingsInDistrict")))
        self.lAmOfFloors.setText(_translate("DialogUpdateRegBuildingsInDistrict", tr("Number of floors")))
        self.lAmOfEntrances.setText(_translate("DialogUpdateRegBuildingsInDistrict", tr("Number of entrances")))
        self.lTotalFloors.setText(_translate("DialogUpdateRegBuildingsInDistrict", tr("Total amount of floors")))
        self.lBuilding_name_reg.setText(_translate("DialogUpdateRegBuildingsInDistrict", tr("Building name")))
        self.lNumberOfBuilding.setText(_translate("DialogUpdateRegBuildingsInDistrict", tr("Number of building")))
        self.pushButtonUpdateData.setText(_translate("DialogUpdateRegBuildingsInDistrict", tr("Update Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogUpdateRegBuildingsInDistrict = QtWidgets.QDialog()
    ui = Ui_DialogUpdateRegBuildingsInDistrict()
    ui.setupUi(DialogUpdateRegBuildingsInDistrict)
    DialogUpdateRegBuildingsInDistrict.show()
    sys.exit(app.exec_())
