# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\Dialog_AddToStateElementEstimatesTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_AddToStateElementEstimatesTable(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(373, 143)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelGesn_id = QtWidgets.QLabel(Dialog)
        self.labelGesn_id.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelGesn_id.setObjectName("labelGesn_id")
        self.gridLayout.addWidget(self.labelGesn_id, 0, 0, 1, 1)
        self.lineGesn_id = QtWidgets.QLineEdit(Dialog)
        self.lineGesn_id.setObjectName("lineGesn_id")
        self.gridLayout.addWidget(self.lineGesn_id, 0, 1, 1, 1)
        self.label_GESN_Unit = QtWidgets.QLabel(Dialog)
        self.label_GESN_Unit.setObjectName("label_GESN_Unit")
        self.gridLayout.addWidget(self.label_GESN_Unit, 1, 0, 1, 1)
        self.lineEdit_GESN_Unit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_GESN_Unit.setObjectName("lineEdit_GESN_Unit")
        self.gridLayout.addWidget(self.lineEdit_GESN_Unit, 1, 1, 1, 1)
        self.label_GESN_name = QtWidgets.QLabel(Dialog)
        self.label_GESN_name.setObjectName("label_GESN_name")
        self.gridLayout.addWidget(self.label_GESN_name, 2, 0, 1, 1)
        self.lineEdit_GESN_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_GESN_name.setObjectName("lineEdit_GESN_name")
        self.gridLayout.addWidget(self.lineEdit_GESN_name, 2, 1, 1, 1)
        self.pushAddData = QtWidgets.QPushButton(Dialog)
        self.pushAddData.setObjectName("pushAddData")
        self.gridLayout.addWidget(self.pushAddData, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", tr("DialogAddToStateElEstimatesTable")))
        self.labelGesn_id.setText(_translate("Dialog", tr("GESN ID")))
        self.label_GESN_Unit.setText(_translate("Dialog", tr("Unit")))
        self.label_GESN_name.setText(_translate("Dialog", tr("GESN name")))
        self.pushAddData.setText(_translate("Dialog", tr("Add Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_AddToStateElementEstimatesTable()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
