# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\Dialog_AddToDirectoryOfWorksTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_AddToDirectoryOfWorksTable(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(437, 143)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelWorkName = QtWidgets.QLabel(Dialog)
        self.labelWorkName.setObjectName("labelWorkName")
        self.gridLayout.addWidget(self.labelWorkName, 0, 0, 1, 1)
        self.lineWorkName = QtWidgets.QLineEdit(Dialog)
        self.lineWorkName.setObjectName("lineWorkName")
        self.gridLayout.addWidget(self.lineWorkName, 0, 1, 1, 1)
        self.label_GESN_ID = QtWidgets.QLabel(Dialog)
        self.label_GESN_ID.setObjectName("label_GESN_ID")
        self.gridLayout.addWidget(self.label_GESN_ID, 1, 0, 1, 1)
        self.lineGESN_ID = QtWidgets.QLineEdit(Dialog)
        self.lineGESN_ID.setObjectName("lineGESN_ID")
        self.lineGESN_ID.setReadOnly(True)
        self.gridLayout.addWidget(self.lineGESN_ID, 1, 1, 1, 1)
        self.label_Unit = QtWidgets.QLabel(Dialog)
        self.label_Unit.setObjectName("label_Unit")
        self.gridLayout.addWidget(self.label_Unit, 2, 0, 1, 1)
        self.line_Unit = QtWidgets.QLineEdit(Dialog)
        self.line_Unit.setObjectName("line_Unit")
        self.gridLayout.addWidget(self.line_Unit, 2, 1, 1, 1)
        self.pushAddData = QtWidgets.QPushButton(Dialog)
        self.pushAddData.setObjectName("pushAddData")
        self.gridLayout.addWidget(self.pushAddData, 3, 1, 1, 1)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", tr("DialogAddToDirectoryOfWorksTable")))
        self.labelWorkName.setText(_translate("Dialog", tr("Work name")))
        self.label_GESN_ID.setText(_translate("Dialog", tr("GESN ID")))
        self.label_Unit.setText(_translate("Dialog", tr("Unit")))
        self.pushAddData.setText(_translate("Dialog", tr("Add Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_AddToDirectoryOfWorksTable()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
