# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogAddDataToAM_works_per_build_GPM.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogAddDataToAM_works_per_build_GPM(object):
    def setupUi(self, DialogAddDataToAM_works_per_build_GPM):
        DialogAddDataToAM_works_per_build_GPM.setObjectName("DialogAddDataToAM_works_per_build_GPM")
        DialogAddDataToAM_works_per_build_GPM.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(DialogAddDataToAM_works_per_build_GPM)
        self.gridLayout.setObjectName("gridLayout")
        self.lBuilding_name = QtWidgets.QLabel(DialogAddDataToAM_works_per_build_GPM)
        self.lBuilding_name.setObjectName("lBuilding_name")
        self.gridLayout.addWidget(self.lBuilding_name, 0, 0, 1, 1)
        self.lWork_name = QtWidgets.QLabel(DialogAddDataToAM_works_per_build_GPM)
        self.lWork_name.setObjectName("lWork_name")
        self.gridLayout.addWidget(self.lWork_name, 1, 0, 1, 1)
        self.lUnit = QtWidgets.QLabel(DialogAddDataToAM_works_per_build_GPM)
        self.lUnit.setObjectName("lUnit")
        self.gridLayout.addWidget(self.lUnit, 2, 0, 1, 1)
        self.lName_of_GPM = QtWidgets.QLabel(DialogAddDataToAM_works_per_build_GPM)
        self.lName_of_GPM.setObjectName("lName_of_GPM")
        self.gridLayout.addWidget(self.lName_of_GPM, 3, 0, 1, 1)
        self.lVol_of_works = QtWidgets.QLabel(DialogAddDataToAM_works_per_build_GPM)
        self.lVol_of_works.setObjectName("lVol_of_works")
        self.gridLayout.addWidget(self.lVol_of_works, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.pushButtonADD_Data = QtWidgets.QPushButton(DialogAddDataToAM_works_per_build_GPM)
        self.pushButtonADD_Data.setObjectName("pushButtonADD_Data")
        self.gridLayout.addWidget(self.pushButtonADD_Data, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.cBBuilding_name = QtWidgets.QComboBox(DialogAddDataToAM_works_per_build_GPM)
        self.cBBuilding_name.setObjectName("cBBuilding_name")
        self.gridLayout.addWidget(self.cBBuilding_name, 0, 1, 1, 2)
        self.cBWork_name = QtWidgets.QComboBox(DialogAddDataToAM_works_per_build_GPM)
        self.cBWork_name.setObjectName("cBWork_name")
        self.gridLayout.addWidget(self.cBWork_name, 1, 1, 1, 2)
        self.cBUnit = QtWidgets.QComboBox(DialogAddDataToAM_works_per_build_GPM)
        self.cBUnit.setObjectName("cBUnit")
        self.gridLayout.addWidget(self.cBUnit, 2, 1, 1, 2)
        self.cBName_of_GPM = QtWidgets.QComboBox(DialogAddDataToAM_works_per_build_GPM)
        self.cBName_of_GPM.setObjectName("cBName_of_GPM")
        self.gridLayout.addWidget(self.cBName_of_GPM, 3, 1, 1, 2)
        self.dsBVol_of_works = QtWidgets.QDoubleSpinBox(DialogAddDataToAM_works_per_build_GPM)
        self.dsBVol_of_works.setDecimals(1)
        self.dsBVol_of_works.setObjectName("dsBVol_of_works")
        self.gridLayout.addWidget(self.dsBVol_of_works, 4, 1, 1, 2)

        self.retranslateUi(DialogAddDataToAM_works_per_build_GPM)
        self.pushButtonADD_Data.clicked.connect(DialogAddDataToAM_works_per_build_GPM.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAddDataToAM_works_per_build_GPM)

    def retranslateUi(self, DialogAddDataToAM_works_per_build_GPM):
        _translate = QtCore.QCoreApplication.translate
        DialogAddDataToAM_works_per_build_GPM.setWindowTitle(_translate("DialogAddDataToAM_works_per_build_GPM",
                                                                        tr("DialogAddDataToAM_works_per_build_GPM")))
        self.lBuilding_name.setText(_translate("DialogAddDataToAM_works_per_build_GPM", tr("Building_name")))
        self.lWork_name.setText(_translate("DialogAddDataToAM_works_per_build_GPM", tr("Work_name")))
        self.lUnit.setText(_translate("DialogAddDataToAM_works_per_build_GPM", tr("Unit")))
        self.lName_of_GPM.setText(_translate("DialogAddDataToAM_works_per_build_GPM", tr("Name_of_GPM")))
        self.lVol_of_works.setText(_translate("DialogAddDataToAM_works_per_build_GPM", tr("Vol_of_works")))
        self.pushButtonADD_Data.setText(_translate("DialogAddDataToAM_works_per_build_GPM", tr("Add Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddDataToAM_works_per_build_GPM = QtWidgets.QDialog()
    ui = Ui_DialogAddDataToAM_works_per_build_GPM()
    ui.setupUi(DialogAddDataToAM_works_per_build_GPM)
    DialogAddDataToAM_works_per_build_GPM.show()
    sys.exit(app.exec_())
