# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\Dialog_Administration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogAdministration(object):
    def setupUi(self, DialogAdministration):
        DialogAdministration.setObjectName("DialogAdministration")
        DialogAdministration.resize(629, 439)
        self.gridLayout = QtWidgets.QGridLayout(DialogAdministration)
        self.gridLayout.setObjectName("gridLayout")
        self.pushAddData = QtWidgets.QPushButton(DialogAdministration)
        self.pushAddData.setObjectName("pushAddData")
        self.gridLayout.addWidget(self.pushAddData, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pushUpdateData = QtWidgets.QPushButton(DialogAdministration)
        self.pushUpdateData.setObjectName("pushUpdateData")
        self.gridLayout.addWidget(self.pushUpdateData, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.pushDeleteData = QtWidgets.QPushButton(DialogAdministration)
        self.pushDeleteData.setObjectName("pushDeleteData")
        self.gridLayout.addWidget(self.pushDeleteData, 0, 5, 1, 1)
        self.pushSearch = QtWidgets.QPushButton(DialogAdministration)
        self.pushSearch.setObjectName("pushSearch")
        self.gridLayout.addWidget(self.pushSearch, 2, 0, 1, 2)
        self.lineSearch = QtWidgets.QLineEdit(DialogAdministration)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout.addWidget(self.lineSearch, 2, 2, 1, 5)
        self.tableView = QtWidgets.QTableView(DialogAdministration)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 7)

        self.retranslateUi(DialogAdministration)
        QtCore.QMetaObject.connectSlotsByName(DialogAdministration)

    def retranslateUi(self, DialogAdministration):
        _translate = QtCore.QCoreApplication.translate
        DialogAdministration.setWindowTitle(_translate("DialogAdministration", tr("DialogAdministration")))
        self.pushAddData.setText(_translate("DialogAdministration", tr("Add user")))
        self.pushUpdateData.setText(_translate("DialogAdministration", tr("Update user")))
        self.pushDeleteData.setText(_translate("DialogAdministration", tr("Delete user")))
        self.pushSearch.setText(_translate("DialogAdministration", tr("Find user")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAdministration = QtWidgets.QDialog()
    ui = Ui_DialogAdministration()
    ui.setupUi(DialogAdministration)
    DialogAdministration.show()
    sys.exit(app.exec_())
