# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogActions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogActions(object):
    def setupUi(self, DialogActions):
        DialogActions.setObjectName("DialogActions")
        DialogActions.resize(356, 225)
        self.gridLayout = QtWidgets.QGridLayout(DialogActions)
        self.gridLayout.setObjectName("gridLayout")
        self.pushSaveData = QtWidgets.QPushButton(DialogActions)
        self.pushSaveData.setObjectName("pushSaveData")
        self.gridLayout.addWidget(self.pushSaveData, 4, 1, 1, 3)
        self.pushPrint = QtWidgets.QPushButton(DialogActions)
        self.pushPrint.setObjectName("pushPrint")
        self.gridLayout.addWidget(self.pushPrint, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.pushPrintPreview = QtWidgets.QPushButton(DialogActions)
        self.pushPrintPreview.setObjectName("pushPrintPreview")
        self.gridLayout.addWidget(self.pushPrintPreview, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.pushSearchData = QtWidgets.QPushButton(DialogActions)
        self.pushSearchData.setObjectName("pushSearchData")
        self.gridLayout.addWidget(self.pushSearchData, 3, 1, 1, 3)
        self.pushAddData = QtWidgets.QPushButton(DialogActions)
        self.pushAddData.setObjectName("pushAddData")
        self.gridLayout.addWidget(self.pushAddData, 0, 1, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 4, 1, 1)
        self.pushDeleteData = QtWidgets.QPushButton(DialogActions)
        self.pushDeleteData.setObjectName("pushDeleteData")
        self.gridLayout.addWidget(self.pushDeleteData, 2, 1, 1, 3)
        self.pushUpdateData = QtWidgets.QPushButton(DialogActions)
        self.pushUpdateData.setObjectName("pushUpdateData")
        self.gridLayout.addWidget(self.pushUpdateData, 1, 1, 1, 3)

        self.retranslateUi(DialogActions)
        QtCore.QMetaObject.connectSlotsByName(DialogActions)

    def retranslateUi(self, DialogActions):
        _translate = QtCore.QCoreApplication.translate
        DialogActions.setWindowTitle(_translate("DialogActions", tr("DialogActions")))
        self.pushSaveData.setText(_translate("DialogActions", tr("Save Data")))
        self.pushPrint.setText(_translate("DialogActions", tr("Print")))
        self.pushPrintPreview.setText(_translate("DialogActions", tr("Print Preview")))
        self.pushSearchData.setText(_translate("DialogActions", tr("Search Data")))
        self.pushAddData.setText(_translate("DialogActions", tr("Add Data")))
        self.pushDeleteData.setText(_translate("DialogActions", tr("Delete Data")))
        self.pushUpdateData.setText(_translate("DialogActions", tr("Update Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogActions = QtWidgets.QDialog()
    ui = Ui_DialogActions()
    ui.setupUi(DialogActions)
    DialogActions.show()
    sys.exit(app.exec_())
