# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogUpdateDataToAM_works_per_build_GPM.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogUpdateDataToAM_works_per_build_GPM(object):
    def setupUi(self, DialogUpdateDataToAM_works_per_build_GPM):
        DialogUpdateDataToAM_works_per_build_GPM.setObjectName("DialogUpdateDataToAM_works_per_build_GPM")
        DialogUpdateDataToAM_works_per_build_GPM.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(DialogUpdateDataToAM_works_per_build_GPM)
        self.gridLayout.setObjectName("gridLayout")
        self.lBuilding_name = QtWidgets.QLabel(DialogUpdateDataToAM_works_per_build_GPM)
        self.lBuilding_name.setObjectName("lBuilding_name")
        self.gridLayout.addWidget(self.lBuilding_name, 0, 0, 1, 1)
        self.lWork_name = QtWidgets.QLabel(DialogUpdateDataToAM_works_per_build_GPM)
        self.lWork_name.setObjectName("lWork_name")
        self.gridLayout.addWidget(self.lWork_name, 1, 0, 1, 1)
        self.lUnit = QtWidgets.QLabel(DialogUpdateDataToAM_works_per_build_GPM)
        self.lUnit.setObjectName("lUnit")
        self.gridLayout.addWidget(self.lUnit, 2, 0, 1, 1)
        self.lName_of_GPM = QtWidgets.QLabel(DialogUpdateDataToAM_works_per_build_GPM)
        self.lName_of_GPM.setObjectName("lName_of_GPM")
        self.gridLayout.addWidget(self.lName_of_GPM, 3, 0, 1, 1)
        self.lVol_of_works = QtWidgets.QLabel(DialogUpdateDataToAM_works_per_build_GPM)
        self.lVol_of_works.setObjectName("lVol_of_works")
        self.gridLayout.addWidget(self.lVol_of_works, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.pushButtonUpdate_Data = QtWidgets.QPushButton(DialogUpdateDataToAM_works_per_build_GPM)
        self.pushButtonUpdate_Data.setObjectName("pushButtonUpdate_Data")
        self.gridLayout.addWidget(self.pushButtonUpdate_Data, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.cBBuilding_name = QtWidgets.QComboBox(DialogUpdateDataToAM_works_per_build_GPM)
        self.cBBuilding_name.setObjectName("cBBuilding_name")
        self.gridLayout.addWidget(self.cBBuilding_name, 0, 1, 1, 2)
        self.cBWork_name = QtWidgets.QComboBox(DialogUpdateDataToAM_works_per_build_GPM)
        self.cBWork_name.setObjectName("cBWork_name")
        self.gridLayout.addWidget(self.cBWork_name, 1, 1, 1, 2)
        self.cBUnit = QtWidgets.QComboBox(DialogUpdateDataToAM_works_per_build_GPM)
        self.cBUnit.setObjectName("cBUnit")
        self.gridLayout.addWidget(self.cBUnit, 2, 1, 1, 2)
        self.cBName_of_GPM = QtWidgets.QComboBox(DialogUpdateDataToAM_works_per_build_GPM)
        self.cBName_of_GPM.setObjectName("cBName_of_GPM")
        self.gridLayout.addWidget(self.cBName_of_GPM, 3, 1, 1, 2)
        self.dsBVol_of_works = QtWidgets.QDoubleSpinBox(DialogUpdateDataToAM_works_per_build_GPM)
        self.dsBVol_of_works.setDecimals(1)
        self.dsBVol_of_works.setObjectName("dsBVol_of_works")
        self.gridLayout.addWidget(self.dsBVol_of_works, 4, 1, 1, 2)

        self.retranslateUi(DialogUpdateDataToAM_works_per_build_GPM)
        self.pushButtonUpdate_Data.clicked.connect(DialogUpdateDataToAM_works_per_build_GPM.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogUpdateDataToAM_works_per_build_GPM)

    def retranslateUi(self, DialogUpdateDataToAM_works_per_build_GPM):
        _translate = QtCore.QCoreApplication.translate
        DialogUpdateDataToAM_works_per_build_GPM.setWindowTitle(_translate("DialogUpdateDataToAM_works_per_build_GPM",
                                                                        tr("DialogUpdateDataToAM_works_per_build_GPM")))
        self.lBuilding_name.setText(_translate("DialogUpdateDataToAM_works_per_build_GPM", tr("Building_name")))
        self.lWork_name.setText(_translate("DialogUpdateDataToAM_works_per_build_GPM", tr("Work_name")))
        self.lUnit.setText(_translate("DialogUpdateDataToAM_works_per_build_GPM", tr("Unit")))
        self.lName_of_GPM.setText(_translate("DialogUpdateDataToAM_works_per_build_GPM", tr("Name_of_GPM")))
        self.lVol_of_works.setText(_translate("DialogUpdateDataToAM_works_per_build_GPM", tr("Vol_of_works")))
        self.pushButtonUpdate_Data.setText(_translate("DialogUpdateDataToAM_works_per_build_GPM", tr("Update Data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogUpdateDataToAM_works_per_build_GPM = QtWidgets.QDialog()
    ui = Ui_DialogUpdateDataToAM_works_per_build_GPM()
    ui.setupUi(DialogUpdateDataToAM_works_per_build_GPM)
    DialogUpdateDataToAM_works_per_build_GPM.show()
    sys.exit(app.exec_())
