# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogCalendarPlanSMR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class DialogCalendarPlanSMR(object):
    def setupUi(self, DialogCalendarPlanSMR):
        DialogCalendarPlanSMR.setObjectName("DialogCalendarPlanSMR")
        DialogCalendarPlanSMR.resize(594, 439)
        self.gridLayout = QtWidgets.QGridLayout(DialogCalendarPlanSMR)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(DialogCalendarPlanSMR)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(230, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButtonOK = QtWidgets.QPushButton(DialogCalendarPlanSMR)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout.addWidget(self.pushButtonOK, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(229, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(DialogCalendarPlanSMR)
        self.pushButtonOK.clicked.connect(DialogCalendarPlanSMR.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogCalendarPlanSMR)

    def retranslateUi(self, DialogCalendarPlanSMR):
        _translate = QtCore.QCoreApplication.translate
        DialogCalendarPlanSMR.setWindowTitle(_translate("DialogCalendarPlanSMR", tr("DialogCalendarPlanSMR")))
        self.pushButtonOK.setText(_translate("DialogCalendarPlanSMR", tr("OK")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogCalendarPlanSMRX = QtWidgets.QDialog()
    ui = DialogCalendarPlanSMR()
    ui.setupUi(DialogCalendarPlanSMRX)
    DialogCalendarPlanSMRX.show()
    sys.exit(app.exec_())
