# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\Diplome\DialogAddUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_DialogAddUser(object):
    def setupUi(self, DialogAddUser):
        DialogAddUser.setObjectName("DialogAddUser")
        DialogAddUser.resize(411, 267)
        self.gridLayout = QtWidgets.QGridLayout(DialogAddUser)
        self.gridLayout.setObjectName("gridLayout")
        self.lUserLogin = QtWidgets.QLabel(DialogAddUser)
        self.lUserLogin.setObjectName("lUserLogin")
        self.gridLayout.addWidget(self.lUserLogin, 0, 0, 1, 1)
        self.lineUserLogin = QtWidgets.QLineEdit(DialogAddUser)
        self.lineUserLogin.setObjectName("lineUserLogin")
        self.gridLayout.addWidget(self.lineUserLogin, 0, 1, 1, 1)
        self.lUserPassword = QtWidgets.QLabel(DialogAddUser)
        self.lUserPassword.setObjectName("lUserPassword")
        self.gridLayout.addWidget(self.lUserPassword, 1, 0, 1, 1)
        self.lineUserPassword = QtWidgets.QLineEdit(DialogAddUser)
        self.lineUserPassword.setObjectName("lineUserPassword")
        self.gridLayout.addWidget(self.lineUserPassword, 1, 1, 1, 1)
        self.lPosition = QtWidgets.QLabel(DialogAddUser)
        self.lPosition.setObjectName("lPosition")
        self.gridLayout.addWidget(self.lPosition, 2, 0, 1, 1)
        self.linePosition = QtWidgets.QLineEdit(DialogAddUser)
        self.linePosition.setObjectName("linePosition")
        self.gridLayout.addWidget(self.linePosition, 2, 1, 1, 1)
        self.pushAddUser = QtWidgets.QPushButton(DialogAddUser)
        self.pushAddUser.setObjectName("pushAddUser")
        self.gridLayout.addWidget(self.pushAddUser, 3, 1, 1, 1)

        self.retranslateUi(DialogAddUser)
        QtCore.QMetaObject.connectSlotsByName(DialogAddUser)

    def retranslateUi(self, DialogAddUser):
        _translate = QtCore.QCoreApplication.translate
        DialogAddUser.setWindowTitle(_translate("DialogAddUser", tr("DialogAddUser")))
        self.lUserLogin.setText(_translate("DialogAddUser", tr("User login")))
        self.lUserPassword.setText(_translate("DialogAddUser", tr("User password")))
        self.lPosition.setText(_translate("DialogAddUser", tr("User role")))
        self.pushAddUser.setText(_translate("DialogAddUser", tr("Add a user")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddUser = QtWidgets.QDialog()
    ui = Ui_DialogAddUser()
    ui.setupUi(DialogAddUser)
    DialogAddUser.show()
    sys.exit(app.exec_())
