# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dmitriy\PycharmProjects\pythonProjectQTDesigner\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Translation import tr


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.Administration = QtWidgets.QMenu(self.menubar)
        self.Administration.setObjectName("Administration")
        self.Administration.setEnabled(False)
        self.About = QtWidgets.QMenu(self.menubar)
        self.About.setObjectName("About")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_5 = QtWidgets.QMenu(self.menu_3)
        self.menu_5.setObjectName("menu_5")
        self.Exit = QtWidgets.QMenu(self.menubar)
        self.Exit.setObjectName("Exit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.SettingsWindowColor = QtWidgets.QAction(MainWindow)
        self.SettingsWindowColor.setObjectName("SettingsWindowColor")
        self.SettingsSWindowSize = QtWidgets.QAction(MainWindow)
        self.SettingsSWindowSize.setObjectName("SettingsSWindowSize")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.Task1 = QtWidgets.QAction(MainWindow)
        self.Task1.setObjectName("Task1")
        self.Task2 = QtWidgets.QAction(MainWindow)
        self.Task2.setObjectName("Task2")
        # self.Task3 = QtWidgets.QAction(MainWindow)
        # self.Task3.setObjectName("Task3")
        self.Task4 = QtWidgets.QAction(MainWindow)
        self.Task4.setObjectName("Task4")
        self.Task5 = QtWidgets.QAction(MainWindow)
        self.Task5.setObjectName("Task5")
        self.action_Administration = QtWidgets.QAction(MainWindow)
        self.action_Administration.setObjectName("action_Administration")
        self.actionEx = QtWidgets.QAction(MainWindow)
        self.actionEx.setObjectName("actionEx")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.Task1)
        self.menu.addAction(self.Task2)
        # self.menu.addAction(self.Task3)
        self.menu.addAction(self.Task4)
        self.menu.addAction(self.Task5)
        self.About.addAction(self.action)
        self.menu_5.addAction(self.action_4)
        self.menu_5.addAction(self.action_5)
        self.menu_3.addAction(self.SettingsWindowColor)
        self.menu_3.addAction(self.SettingsSWindowSize)
        self.menu_3.addAction(self.menu_5.menuAction())
        self.Administration.addAction(self.action_Administration)
        self.Exit.addSeparator()
        self.Exit.addAction(self.action_exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.About.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.Administration.menuAction())
        self.menubar.addAction(self.Exit.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", tr("MainWindow")))
        self.menu.setTitle(_translate("MainWindow", tr("Tasks")))
        self.Administration.setTitle(_translate("MainWindow", tr("Administration")))
        self.About.setTitle(_translate("MainWindow", tr("About")))
        self.menu_3.setTitle(_translate("MainWindow", tr("Settings")))
        self.menu_5.setTitle(_translate("MainWindow", tr("Language settings of the app")))
        self.Exit.setTitle(_translate("MainWindow", tr("Exit")))
        self.SettingsWindowColor.setText(_translate("MainWindow", tr("Windows' theme settings")))
        self.SettingsSWindowSize.setText(_translate("MainWindow", tr("Settings of size of the MainWindow")))
        self.action_4.setText(_translate("MainWindow", tr("Russian language")))
        self.action_5.setText(_translate("MainWindow", tr("English language")))
        self.Task1.setText(_translate("MainWindow", tr("Calendar schedule of electrical installation"
                                                       " works based on a subcontract agreement")))
        self.Task2.setText(_translate("MainWindow", tr("Schedule of GPM works at the facilities")))
        # self.Task3.setText(_translate("MainWindow", tr("Weekly-daily schedule"
        #                                                " execution of general construction works at the facilities")))
        self.Task4.setText(_translate("MainWindow", tr("Statement of personnel requirements")))
        self.Task5.setText(_translate("MainWindow", tr("Weekly-daily schedule of electrical installation works "
                                                       "on objects")))
        self.actionEx.setText(_translate("MainWindow", tr("Exit")))
        self.action_exit.setText(_translate("MainWindow", tr("Exit to the desktop")))
        self.action_Administration.setText(_translate("MainWindow", tr("Administration")))
        self.action.setText(_translate("MainWindow", tr("About")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
